# Generated by Django 4.2 on 2026-05-23 21:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_name', models.CharField(max_length=150)),
                ('quote_email', models.EmailField(max_length=254)),
                ('quote_phone', models.CharField(max_length=30)),
                ('quote_serviceType', models.CharField(choices=[('sea', 'Sea Shipping'), ('air', 'Air Freight'), ('vehicle', 'Vehicle Shipment'), ('other', 'Other Types')], max_length=30)),
                ('quoteFromCountry', models.CharField(max_length=100)),
                ('quoteToCountry', models.CharField(max_length=100)),
                ('quote_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
