# Generated by Django 4.2 on 2026-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0005_alter_contactmessage_uuid_alter_newsletter_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('treated', 'Treated'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
