# Generated by Django 4.2 on 2026-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0006_quoterequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('treated', 'Treated'), ('deleted', 'Deleted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
