# Generated by Django 4.2 on 2026-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0008_quoterequest_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
