# Generated by Django 4.2 on 2026-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0012_alter_address_address_line_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
