# Generated by Django 4.2 on 2026-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0013_order_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(max_length=50),
        ),
    ]
