# Generated by Django 4.2 on 2026-06-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0014_alter_order_receiver_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_destination_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
