# Generated by Django 4.2 on 2026-06-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0019_orderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
