# Generated by Django 4.2 on 2026-06-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0024_invoice_payment_invoicelineitem_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='charge_type',
            field=models.CharField(choices=[('freight', 'Car Shipping'), ('freight', 'Container Shipping'), ('freight', 'Freight / Shipping'), ('handling', 'Handling Fee'), ('insurance', 'Insurance'), ('storage', 'Storage Fee'), ('documentation', 'Documentation Fee'), ('other', 'Other')], db_index=True, default='freight', max_length=20),
        ),
    ]
