# Generated by Django 4.2 on 2026-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0025_alter_invoicelineitem_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsdutyrecord',
            name='clearance_port',
            field=models.CharField(blank=True, help_text='Port of clearance e.g. Lagos (Apapa), Tema, Takoradi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customsdutyrecord',
            name='customs_agent',
            field=models.CharField(blank=True, help_text='Name of the clearing agent at destination', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customsdutyrecord',
            name='duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applicable duty rate as a percentage e.g. 20.00 for 20%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customsdutyrecord',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System commodity code e.g. 8703.23', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customsdutyrecord',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT or levy amount in the same duty_currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('cleared', 'Cleared'), ('held', 'Held at Port'), ('rejected', 'Rejected')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_direction',
            field=models.CharField(choices=[('outbound', 'Outbound (UK → West Africa)'), ('inbound', 'Inbound (West Africa → UK)')], db_index=True, default='outbound', max_length=20),
        ),
    ]
