# Generated by Django 4.2 on 2026-06-24 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainWebsite.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainWebsite', '0026_customsdutyrecord_clearance_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('bill_of_lading', 'Bill of Lading'), ('airway_bill', 'Airway Bill (AWB)'), ('packing_list', 'Packing List'), ('commercial_invoice', 'Commercial Invoice'), ('certificate_of_origin', 'Certificate of Origin'), ('customs_declaration', 'Customs Declaration'), ('import_duty_receipt', 'Import Duty Receipt'), ('delivery_order', 'Delivery Order'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('document_number', models.CharField(blank=True, help_text='e.g. BOL number, AWB number, declaration reference', max_length=100, null=True)),
                ('file', models.FileField(blank=True, help_text='PDF, JPG or PNG — max 10MB', null=True, upload_to=mainWebsite.models.customs_document_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_documents_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_documents', to='mainWebsite.warehouseitem')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customs_documents', to='mainWebsite.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customsdocument',
            index=models.Index(fields=['shipment', 'document_type'], name='mainWebsite_shipmen_6ffa30_idx'),
        ),
        migrations.AddIndex(
            model_name='customsdocument',
            index=models.Index(fields=['item', 'document_type'], name='mainWebsite_item_id_08e1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='customsdocument',
            index=models.Index(fields=['status'], name='mainWebsite_status_2fc5fd_idx'),
        ),
    ]
