# Generated by Django 4.2 on 2026-06-26 13:15

import dashboard.utils.file_handler
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainWebsite', '0027_customsdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('shipping_label', 'Shipping Label'), ('delivery_note', 'Delivery Note'), ('invoice', 'Invoice'), ('customs_form', 'Customs Form'), ('payment_proof', 'Payment Proof'), ('reimbursement', 'Reimbursement Receipt'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=dashboard.utils.file_handler.document_upload_to)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('generated', models.BooleanField(default=False, help_text='True if system-generated (label/note), False if manually uploaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mainWebsite.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mainWebsite.order')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mainWebsite.shipment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Document',
                'verbose_name_plural': 'Uploaded Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
