# Generated by Django 4.2 on 2026-06-27 14:27

from django.db import migrations, models
import uuid

def generate_uuids(apps, schema_editor):
    UserProfile = apps.get_model('mainWebsite', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.uuid = uuid.uuid4()
        profile.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0029_userprofile'),  # ← keep whatever was here originally
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=False, editable=False),  # unique=False first
        ),
        migrations.RunPython(generate_uuids, migrations.RunPython.noop),  # fill unique values
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),  # now make unique
        ),
    ]