# Generated by Django 4.2 on 2026-06-29 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainWebsite', '0031_userprofile_is_online_userprofile_last_login_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TDSSUK Global Services Ltd', max_length=200)),
                ('company_email', models.EmailField(default='', max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=30)),
                ('company_address', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('website_url', models.URLField(blank=True)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('email_from_name', models.CharField(blank=True, max_length=100)),
                ('email_from_address', models.EmailField(blank=True, max_length=254)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('session_timeout_mins', models.PositiveIntegerField(default=60)),
                ('require_2fa', models.BooleanField(default=False)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('size_kb', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
