# Generated by Django 4.2 on 2026-06-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0034_supportticket_submitter_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_source', to='mainWebsite.supportticket'),
        ),
    ]
